name: DoubleSubtitle
options:
  bundleIdPrefix: com.doublesubtitle
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: false

targets:
  DoubleSubtitle:
    type: application
    platform: iOS
    sources:
      - path: DoubleSubtitle
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: DoubleSubtitle/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.doublesubtitle.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
    info:
      path: DoubleSubtitle/Info.plist
      properties:
        CFBundleName: DoubleSubtitle
        CFBundleDisplayName: 双语字幕
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "需要麦克风权限来捕获音频进行语音识别"
        NSSpeechRecognitionUsageDescription: "需要语音识别权限来识别音频内容"
        NSAppleMusicUsageDescription: "需要访问Apple Music来捕获系统音频"
        UIBackgroundModes:
          - audio
        BGTaskSchedulerPermittedIdentifiers:
          - com.doublesubtitle.app.translation
    entitlements:
      path: DoubleSubtitle/DoubleSubtitle.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.doublesubtitle.app

  AudioCaptureExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: AudioCaptureExtension
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: AudioCaptureExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.doublesubtitle.app.AudioCaptureExtension
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SKIP_INSTALL: YES
    entitlements:
      path: AudioCaptureExtension/AudioCaptureExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.doublesubtitle.app

schemes:
  DoubleSubtitle:
    build:
      targets:
        DoubleSubtitle: all
        AudioCaptureExtension: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
